### ISSUE TITLE
include和exclude冲突

### ISSUE THREAD

**Issue by lovewenzi** [evrone/postcss-px-to-viewport#109]
include和exclude冲突
单独设置一个都有效，如果同时设置就include生效
![image](https://user-images.githubusercontent.com/29187594/127458134-f2e4d4db-99dc-4609-862f-7a5f94a2fcbf.png)

**Comment by lovewenzi** [comment]
写文档的兄弟祝你平安

**Comment by lzm0x219** [comment]
?

**Comment by oxiran** [comment]
> include和exclude冲突 单独设置一个都有效，如果同时设置就include生效 ![image](https://user-images.githubusercontent.com/29187594/127458134-f2e4d4db-99dc-4609-862f-7a5f94a2fcbf.png)

大哥，这不是很差正常？包含和不包含本来就是互斥的
