### ISSUE TITLE
has config like pxtorem propList ?

### ISSUE THREAD

**Issue by wangjinyang** [evrone/postcss-px-to-viewport#12]
[link](https://www.npmjs.com/package/postcss-pxtorem)
https://www.npmjs.com/package/postcss-pxtorem

propList (Array) The properties that can change from px to rem.
Values need to be exact matches.
Use wildcard * to enable all properties. Example: ['*']
Use * at the start or end of a word. (['*position*'] will match background-position-y)
Use ! to not match a property. Example: ['*', '!letter-spacing']
Combine the "not" prefix with the other prefixes. Example: ['*', '!font*']

**Comment by chernobelenkiy** [comment]
@wangjinyang we've added PR with that option, now you can use it freely with the package version `1.0.0`.
