### ISSUE TITLE
how can i use this with vue-cli3.0

### ISSUE THREAD

**Issue by tihssiefiL** [evrone/postcss-px-to-viewport#13]

**Comment by moonou** [comment]
1. `npm` or `yarn` to install
2. change `postcss.config.js`
``` javascript
module.exports = {
  plugins: {
    ...
    'postcss-px-to-viewport': {
      // options
    }
  }
}
```

**Comment by chernobelenkiy** [comment]
@moonou thanks, we've added this information to our `readme.md` file. Since there are no more questions, I close this issue.
