### ISSUE TITLE
include 无法单独处理scss文件

### ISSUE THREAD

**Issue by gitsheny** [evrone/postcss-px-to-viewport#136]
include貌似只能对vue文件生效。假如vue导入外部scss，include  vue文件时生效，include vue引入的scss文件时不生效

**Comment by yakabito** [comment]
咋解决的哥们？

**Comment by gitsheny** [comment]
> 咋解决的哥们？

修改源码，筛选指定内容

**Comment by AprilLemon** [comment]
> > 咋解决的哥们？
> 
> 修改源码，筛选指定内容

可以提供给下代码吗 感谢
