### ISSUE TITLE
能请教下怎么写的吗

### ISSUE THREAD

**Issue by Yahuizhang** [evrone/postcss-px-to-viewport#143]
我不用vw了，改成自动转换rem了。。。
然后在写个媒体查询

_Originally posted by @frank-pian in https://github.com/evrone/postcss-px-to-viewport/issues/130#issuecomment-1110105428_

**Comment by wswmsword** [comment]
试一下我最近写的插件，在 postcss-px-to-viewport 前使用，会自动插入媒体查询，会限制 vw 的最大宽度。

https://github.com/wswmsword/postcss-mobile-forever
