### ISSUE TITLE
selectorBlackList won't take effect

### ISSUE THREAD

**Issue by jiankafei** [evrone/postcss-px-to-viewport#15]

**Comment by nikli2009** [comment]
not sure if the author still accept merging... @jiankafei 
I replace the selectorBlackList with filePathBlackList. so if you want to skip some files. you can do it using this prop.
[Package](https://github.com/nikli2009/postcss-px-to-viewport)

**Comment by jiankafei** [comment]
OK I'll try

**Comment by chernobelenkiy** [comment]
@jiankafei  if you mean to exclude some source folders, then we've add PR with `exclude` option, thanks to @msidolphin
You can check out this issue #8 for more information.
