### ISSUE TITLE
无法找到模块“postcss-px-to-viewport”的声明文件

### ISSUE THREAD

**Issue by sz-hhb** [evrone/postcss-px-to-viewport#162]
import postcssPxToViewport from "postcss-px-to-viewport"的ts
无法找到模块“postcss-px-to-viewport”的声明文件。
  尝试使用 `npm i --save-dev @types/postcss-px-to-viewport` (如果存在)，或者添加一个包含 `declare module 'postcss-px-to-viewport';` 的新声明(.d.ts)文件ts(7016)

**Comment by czmCWH** [comment]
@sz-hhb 无法找到模块“postcss-px-to-viewport”的声明文件，请教下这个问题怎么解决🙏

**Comment by sz-hhb** [comment]
@czmCWH 添加一个包含 declare module 'postcss-px-to-viewport'; 的新声明(.d.ts)文件。 可以试试看能不能解决

**Comment by czmCWH** [comment]
@sz-hhb 是的，加个类型声明，然后需要在 import pxtovw from 'postcss-px-to-viewport' 导入时添加 // @ts-ignore 忽略才可以。已解决，感谢啦🙏
// @ts-ignore
import pxtovw from 'postcss-px-to-viewport'

**Comment by NobodyDJ** [comment]
@czmCWH 感谢大佬 添加//@ts-ignore成功了
