### ISSUE TITLE
Spec for v0.1.x

### ISSUE THREAD

**Issue by KODerFunk** [evrone/postcss-px-to-viewport#2]
- [ ] detecting value orientation function (vertical/horizontal)
- [ ] reading directives in css-comments around properties `/\/\/\s+viewport:(enable|disable)\s+DetectDirection/`
- [ ] remove option `viewportUnit: 'vw'`
- [ ] add option `detectDirection: false`
- [ ] convert vertical oriented values between/around toggling `DetectDirection`

**Comment by dxcqcv** [comment]
why prepare to  remove `viewportUnit 'vw'`?

**Comment by KODerFunk** [comment]
@dxcqcv needs adaptation for width and height.

**Comment by KODerFunk** [comment]
OK, we are back)
Roadmap is not relevant.
We will simply maintain the actual status of package, listening to the needs of developers.
