### ISSUE TITLE
Similar to the promotion page, there is a minimum width, on the mobile end is full screen, in the PC is centered, how to modify the configuration

### ISSUE THREAD

**Issue by CaniceZ** [evrone/postcss-px-to-viewport#28]
![1552300274(1)](https://user-images.githubusercontent.com/23026625/54117655-4053e300-442c-11e9-8bc1-c5b0b8148da9.jpg)
我之前是自己写是这样写的如下：

(function (doc, win) {
--
  | var docEl = doc.documentElement,
  | resizeEvt = 'orientationchange' in window ? 'orientationchange' : 'resize',
  | recalc = function () {
  | var clientWidth = docEl.clientWidth;
  | if (!clientWidth) return;
  | if(clientWidth>415){
  | docEl.style.fontSize = 100 * (414 / 640) + 'px';
  | }else{
  | docEl.style.fontSize = 100 * (clientWidth / 640) + 'px';
  | }
  | };
  |  
  | if (!doc.addEventListener) return;
  | win.addEventListener(resizeEvt, recalc, false);
  | doc.addEventListener('DOMContentLoaded', recalc, false);
  | })(document, window);

有没有哪个配置可以修改视图的阈值类似超过屏幕超过750就按750的来计算

**Comment by CaniceZ** [comment]
sorry，I thought you were Chinese。My question is using the 750 configuration when the screen is over 750?

**Comment by KODerFunk** [comment]
@CaniceZ try config like this:
```js
module.exports = {
  plugins: {
    ...
    'postcss-px-to-viewport': {
      viewportWidth: 640,
      landscape: true,
      landscapeUnit: 'px',
      landscapeWidth: 640 * 100 / 414
    }
  }
}
```
Maybe in future we will add the ability to pass function to `viewportWidth`, like `function (px) { return ...; }`.

**Comment by CaniceZ** [comment]
> @CaniceZ 750 is your design width? Try config like this:
> 
> ```js
> module.exports = {
>   plugins: {
>     ...
>     'postcss-px-to-viewport': {
>       viewportWidth: 750,
>       landscape: true,
>       landscapeUnit: 'px',
>       landscapeWidth: 750 * 100 / 414
>     }
>   }
> }
> ```
> 
> Maybe in future we will add the ability to pass function to `viewportWidth`, like `function (px) { return ...; }`.

Thank you and look forward to your update

**Comment by KODerFunk** [comment]
@CaniceZ `landscape*` options already in project: https://github.com/evrone/postcss-px-to-viewport/blob/master/README_CN.md#配置参数

**Comment by VisonM** [comment]
It seems that this library cannot achieve this function, he can only calculate the relative vw value of the element according to the design draft. But the actual screen width is unpredictable. For example, the width of a div is 75px, which is converted to 10vw. But unfortunately, when the width of the browser is large, such as 1920, the 10vw will become very large. We can't center it at 750px. The only way is to jump to an iframe page and set the iframe to 750px to display the URL of the current page.
