### ISSUE TITLE
How to restore it back？

### ISSUE THREAD

**Issue by LaoliangGitHub** [evrone/postcss-px-to-viewport#30]
After the success of the tutorial, there is no configuration, will automatically modify the restore to the previous css

**Comment by KODerFunk** [comment]
@LaoliangGitHub hi!
Why you need reverse postcss transformations? Can you give a link to an example of what you want?

**Comment by harlanjun** [comment]
How to prohibit conversion above a certain px.  
Is it possible to join maxPixelValue
At 750px we don't want to convert
