### ISSUE TITLE
Height has been converted to `vw`. How do I convert height to `vh`? height 都转换成vw了，请问如何将height转换成vh

### ISSUE THREAD

**Issue by zhangyq233** [evrone/postcss-px-to-viewport#35]
height 都转换成vw了，请问如何将height转换成vh

**Comment by msidolphin** [comment]
`viewportUnit`, `fontViewportUnit`

**Comment by KODerFunk** [comment]
@zhangyq233 Also, maybe you can try options `landscape`, `landscapeUnit`, `landscapeWidth` for scaling configuration of horizontal orientation.

**Comment by ShawLyon** [comment]
> @zhangyq233 Also, maybe you can try options `landscape`, `landscapeUnit`, `landscapeWidth` for scaling configuration of horizontal orientation.

非常棒

**Comment by KODerFunk** [comment]
Related issues: #16, #28, #32, #38.
