### ISSUE TITLE
How to convert in inline style?

### ISSUE THREAD

**Issue by airen** [evrone/postcss-px-to-viewport#4]
@evrone: For example, I have some inline styles, how do I get `px` to `vw`. eg:

```html
<div style="width: 100px"></div>
```

I hope it can work:

```html
<div style="width:13.3333vw"></div>
```

Especially in the react project.

**Comment by alicksnake22** [comment]
@airen 你好，看了你的文章的。如果过滤第三方库不进行转换？

**Comment by Adamwu1992** [comment]
And, if I have a img tag like this:
```html
<img src="url" width="100" />
```
I hope it can be converted to:
```html
<img src="url" style="width:13.333vw" />
```
😄😄I don't know if this situation is rare

**Comment by KODerFunk** [comment]
@airen, @alicksnake22, @Adamwu1992 good question, but sorry, not for this solution. `postcss-px-to-viewport` is a plugin for PostCSS.

**Comment by 657447158** [comment]
> @evrone: For example, I have some inline styles, how do I get `px` to `vw`. eg:
> 
> ```
> <div style="width: 100px"></div>
> ```
> 
> I hope it can work:
> 
> ```
> <div style="width:13.3333vw"></div>
> ```
> 
> Especially in the react project.

大漠老师，关于行内样式px转vw的问题解决了吗？

**Comment by vvni** [comment]
@657447158  行内样式的转换与这个插件无关，你可以用公式进行转换

**Comment by vvni** [comment]
@657447158 const getVwUnit = (num: number): number => num / window.screen.width * 100，num是px单位
