### ISSUE TITLE
How to use in clojurescript？

### ISSUE THREAD

**Issue by qdhaiqiang** [evrone/postcss-px-to-viewport#42]
I am using reagent+hiccup+shadow-cljs in my web project, I also want to use this plugins.

There are a lot of introductions in blog, included Parcel、webpack、Gulp and so on，then how can i use in clojurescript project？

**Comment by KODerFunk** [comment]
This is only plugin for PostCSS and you already have answer from PostCSS (host-lib of this plugin) creator @ai: https://github.com/postcss/postcss/issues/1300

From me some research topic: https://www.reddit.com/r/Clojure/comments/8mco9g/how_to_use_tailwind_css_with_clojurescript/

**Comment by qdhaiqiang** [comment]
Thank you very much, and I had push my own plugins on github.
It is used on emacs conveniently.

[px2vw-emcas-plugin](https://github.com/qdhaiqiang/px2vw-emcas-plugin)

Thanks again
