### ISSUE TITLE
最低转化视口,是否可以提供一个最低转换视口的API

### ISSUE THREAD

**Issue by smz8023** [evrone/postcss-px-to-viewport#45]
是否可以提供一个最低转换视口的API，比如说，视口到某一定宽度时候，不在进行转换，有个最低标准

**Comment by 3344567** [comment]
minPixelValue,默认是1px

**Comment by CaniceZ** [comment]
配置文件改成rem
index.html根据实际情况做以下修改
<meta name="viewport" content="width=750, user-scalable=no" />
  html{
      max-width: 750px;
      margin: 0 auto;
    }
    #app{
      max-width: 750px;
      position: relative;
    }

**Comment by 3344567** [comment]
现在已经前后端分离了，难不成你的项目还在不分离阶段？scss转css是预编译

**Comment by CaniceZ** [comment]
前后分离的没有index.html吗。。。我是用vue加这个插件，需求和你差不多

**Comment by 3344567** [comment]
这不是我的需求，是楼主的需求。我感觉这个需求不合理

**Comment by CaniceZ** [comment]
这种需求很常见。。。不然你wap端项目在PC端打开会拉伸成什么样？PC端居中显示是比较省时省力的解决方案

**Comment by smz8023** [comment]
我的意思是:在浏览器缩小到1400的时候，px就不转换vw了。
 
---原始邮件---
发件人: "xianyu"<notifications@github.com&gt;
发送时间: 2019年12月4日(星期三) 晚上6:32
收件人: "evrone/postcss-px-to-viewport"<postcss-px-to-viewport@noreply.github.com&gt;;
抄送: "smz8023"<345398278@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [evrone/postcss-px-to-viewport] 最低转化视口,是否可以提供一个最低转换视口的API (#45)



这种需求很常见。。。不然你wap端项目在PC端打开会拉伸成什么样？PC端居中显示是比较省时省力的解决方案

**Comment by 3344567** [comment]
> 不然你wap端项目在PC端打开会拉伸成什么样？PC端居中显示是比较省时省力的解决方案

所以，请百度预编译

**Comment by KODerFunk** [comment]
@smz8023 您可以默认使用mediaQuery选项为false，因此可以使用媒体点来描述不进行转换的变体:
```scss
@media (max-width: 1440px) {
  .some-class {
    width: 100px;
    font-size: 18px;
  }
}
```

**Comment by wswmsword** [comment]
可以试下 [postcss-mobile-to-multi-displays](https://github.com/wswmsword/postcss-mobile-to-multi-displays)，你设置最大宽度之后，这个插件会添加媒体查询，在横屏和桌面端会展示居中的移动端视图。
