### ISSUE TITLE
How to convert `px` to `vw` in `@keyframes`? @keyframes中的px无法转成vw

### ISSUE THREAD

**Issue by kagari2613** [evrone/postcss-px-to-viewport#46]
如何配置，可以让keyframes中的px转为vw

**Comment by dupengdl** [comment]
设置`mediaQuery: true`可以转换

**Comment by kagari2613** [comment]
> 设置`mediaQuery: true`可以转换

感谢。

**Comment by KODerFunk** [comment]
Related issues: #34, #43.

Question:
> How to convert `px` to `vw` in `@keyframes`?

Answer:
> Set `mediaQuery: true` to convert.

@dupengdl thanks you!
