### ISSUE TITLE
How `exclude` some files? / 求助 exclude应该怎么写？

### ISSUE THREAD

**Issue by belief-cyf** [evrone/postcss-px-to-viewport#48]
插件只支持exclude选项 不支持include
请问我这种目录结构想让插件只处理bbb文件夹下的文件 其他的文件都不处理exclude应该怎么写？
试了很多次正则表达式都不行，求大佬助力！
![image](https://user-images.githubusercontent.com/19991842/76278360-7ab5c180-62c6-11ea-88af-73e7c5a50522.png)

**Comment by KODerFunk** [comment]
@belief-cyf 请举一个例子。
1）您的原始CSS代码
2）结果代码
3）设置

**Comment by nigiwen** [comment]
？？？怎么解决的
