### ISSUE TITLE
include设置无效

### ISSUE THREAD

**Issue by 1870390731** [evrone/postcss-px-to-viewport#53]
"postcss-px-to-viewport": {
            "viewportWidth": 375,
            "minPixelValue": 1,
            include: [path.resolve('src/views/mobile')]
        }
这样设置以后，views下面的web文件夹下面的所有vue文件还是转换成了vw，请问下这是什么原因？

**Comment by starlight02** [comment]
>- include (Array or Regexp) 如果设置了include，那将只有匹配到的文件才会被转换，例如只转换 'src/mobile' 下的文件 ` (include: /\/src\/mobile\//)`
>    - 如果值是一个正则表达式，将包含匹配的文件，否则将排除该文件
>    - 如果传入的值是一个数组，那么数组里的值必须为正则

`include` 必须是正则表达式，但是问题是，我按文档上设置的 `include: /\/src\/mobile\//` 也无效，有人知道怎么回事吗？

**Comment by 1870390731** [comment]
> > * include (Array or Regexp) 如果设置了include，那将只有匹配到的文件才会被转换，例如只转换 'src/mobile' 下的文件 ` (include: /\/src\/mobile\//)`
> >   
> >   * 如果值是一个正则表达式，将包含匹配的文件，否则将排除该文件
> >   * 如果传入的值是一个数组，那么数组里的值必须为正则
> 
> `include` 必须是正则表达式，但是问题是，我按文档上设置的 `include: /\/src\/mobile\//` 也无效，有人知道怎么回事吗？

我也是按文档上设置无效

**Comment by zmaoo** [comment]
include 是上个月才做的，还没有 release，但是文档已经提前更新了，太坑了。。。

**Comment by IceApriler** [comment]
Hey, you can use the github repository code and switch to NPM after the NPM package is released.

嗨，你们可以先使用github仓库的代码，等npm包发布后再切换到npm。

```bash
npm i https://github.com/evrone/postcss-px-to-viewport --save-dev
```

**Comment by starlight02** [comment]
> Hey, you can use the github repository code and switch to NPM after the NPM package is released.
> 
> 嗨，你们可以先使用github仓库的代码，等npm包发布后再切换到npm。
> 
> 
> npm i https://github.com/evrone/postcss-px-to-viewport --save-dev

感谢提供解决方案！

Thank you for providing the solution.

**Comment by mqhe2007** [comment]
> include 是上个月才做的，还没有 release，但是文档已经提前更新了，太坑了。。。

包括忽略的注释语法，包不发就更新文档，太误导人了。

**Comment by viphsx123** [comment]
还没发包到npm吗

**Comment by git-lt** [comment]
不兼容windows环境的下路径，path需要处理一下

**Comment by 1870390731** [comment]
> > Hey, you can use the github repository code and switch to NPM after the NPM package is released.
> > 嗨，你们可以先使用github仓库的代码，等npm包发布后再切换到npm。
> > npm i https://github.com/evrone/postcss-px-to-viewport --save-dev
> 
> 感谢提供解决方案！
> 
> Thank you for providing the solution.

能告诉一下具体怎么操作吗?

**Comment by 1870390731** [comment]
> > Hey, you can use the github repository code and switch to NPM after the NPM package is released.
> > 嗨，你们可以先使用github仓库的代码，等npm包发布后再切换到npm。
> > npm i https://github.com/evrone/postcss-px-to-viewport --save-dev
> 
> 感谢提供解决方案！
> 
> Thank you for providing the solution.

能告诉一下具体怎么操作吗?我用github下载下来的怎么是postcss-px-to-viewport-master这个文件夹名

**Comment by 1870390731** [comment]
> 还没发包到npm吗

刚试了下,还是不行

**Comment by younth** [comment]
为啥不发npm啊....

**Comment by codetwl** [comment]
![image](https://user-images.githubusercontent.com/57863979/103366103-ab3c4580-4afc-11eb-8de2-6f37c6e4ca17.png)
明明设置了按照类屏蔽不转化为px，无效

**Comment by xiaofan9** [comment]
![image](https://user-images.githubusercontent.com/16103130/103516529-af28e880-4eab-11eb-84f5-af7422251add.png)
好像这样设置，依旧无效，懵逼了

**Comment by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
include的 还没发包嘛，设置完了 还是不好使啊 …………………………………………………………

**Comment by xiaofan9** [comment]
> include的 还没发包嘛，设置完了 还是不好使啊 …………………………………………………………

还没有。一直卡着

**Comment by chaos-zhu** [comment]
em...为啥不发，大佬还在过年吗😂

**Comment by flyyuan** [comment]
到现在还没发....

**Comment by niefangfang** [comment]
等着大佬发。。。。

**Comment by niefangfang** [comment]
> 好像这样设置，依旧无效，懵逼了

你的设置好了吗，为啥我的用了 npm i https://github.com/evrone/postcss-px-to-viewport --save-dev 还是不好

**Comment by lsc9** [comment]
file path is below: 

`'D:\\Web_data\\Web_project\\mico_code\\yoho-mobile\\src\\pages\\salaryWithdraw\\withdraw\\pages\\withdraw_home\\index.vue'`

so regexp must be like below:

```
include:[
    /node_modules[\\/]vant[\\/]/,
    /[\\/]src[\\/]pages[\\/]salaryWithdraw[\\/]/
]
```
`/\/src\/pages\/salaryWithdraw/` is bad.

**Comment by usercao** [comment]
今天为止还是没发😅

**Comment by winjeysong** [comment]
因为原作者迟迟不发布，所以我fork了一份，发布了一个包含 `include` 配置的包：[postcss-px-to-viewport-update](https://www.npmjs.com/package/postcss-px-to-viewport-update?activeTab=readme)，大家可以在原作者release之后再换回来。

hi guys, i forked this repo & published a package with `include` -  [postcss-px-to-viewport-update](https://www.npmjs.com/package/postcss-px-to-viewport-update?activeTab=readme). you can use this one until this repo releases a new version.

**Comment by guikuan** [comment]
> 因为原作者迟迟不发布，所以我fork了一份，发布了一个包含 `include` 配置的包：[postcss-px-to-viewport-update](https://www.npmjs.com/package/postcss-px-to-viewport-update?activeTab=readme)，大家可以在原作者release之后再换回来。
> 
> hi guys, i forked this repo & published a package with `include` - [postcss-px-to-viewport-update](https://www.npmjs.com/package/postcss-px-to-viewport-update?activeTab=readme). you can use this one until this repo releases a new version.

太感谢了，很好用，敏感肌也能用🤲

**Comment by 1282814653** [comment]
这都 一年半了吧 ...................

**Comment by wenmua** [comment]
这都一年半了吧....大佬 还没更新处理 include 的问题吗

**Comment by tilemoon** [comment]
> 这都一年半了吧....大佬 还没更新处理 include 的问题吗

还是自己发个包吧，别指望了

**Comment by qidasheng369** [comment]
是不是大佬太忙了？把这茬事给忘了吗

**Comment by bailuochen** [comment]
看来是忘记了

**Comment by bailuochen** [comment]
> 因为原作者迟迟不发布，所以我fork了一份，发布了一个包含 `include` 配置的包：[postcss-px-to-viewport-update](https://www.npmjs.com/package/postcss-px-to-viewport-update?activeTab=readme)，大家可以在原作者release之后再换回来。
> 
> hi guys, i forked this repo & published a package with `include` - [postcss-px-to-viewport-update](https://www.npmjs.com/package/postcss-px-to-viewport-update?activeTab=readme). you can use this one until this repo releases a new version.

感谢🙏，把之前安装的postcss-px-to-viewport卸载后，安装这个非常好用。

**Comment by xiang1128** [comment]
作者已经去世了吗  这么久不更新

**Comment by lzm0x219** [comment]
> 作者已经去世了吗 这么久不更新

你以为你很幽默吗？🙄

**Comment by xiang1128** [comment]
> > 这么久没有更新
> 
> 你以为你很幽默吗？🙄

我是认真的

**Comment by chaos-zhu** [comment]
> > > 这么久没有更新
> > 
> > 
> > 你以为你很幽默吗？🙄
> 
> 我是认真的

上面不是有人发了吗，还这么咒人......

**Comment by doerme** [comment]
4年没更新了  4 years no update

**Comment by ranran310** [comment]
postcss-px-to-viewport插件已弃用，使用postcss-px-to-viewport-8-plugin代替

**Comment by pandaXiong01** [comment]
发了npm包支持 include  @pandaxiong1992/postcss-px-to-viewport
this npm package support include

**Comment by ELing9527** [comment]
现在还有更新，虽然发布了postcss-px-to-viewport-8-plugin 但是我这个项目由一些其他的冲突了啊啊啊

**Comment by nanfb** [comment]
> 因为原作者迟迟不发布，所以我fork了一份，发布了一个包含 `include` 配置的包：[postcss-px-to-viewport-update](https://www.npmjs.com/package/postcss-px-to-viewport-update?activeTab=readme)，大家可以在原作者release之后再换回来。
> 
> hi guys, i forked this repo & published a package with `include` - [postcss-px-to-viewport-update](https://www.npmjs.com/package/postcss-px-to-viewport-update?activeTab=readme). you can use this one until this repo releases a new version.

为什么我直接全部失效了
