### ISSUE TITLE
create-react-app用了该插件但是写样式的时候px并没有转换为vw

### ISSUE THREAD

**Issue by XdyGoGo** [evrone/postcss-px-to-viewport#76]

**Comment by xuxiaoxiao312** [comment]
遇到了同样的问题，请问解决了吗

**Comment by XdyGoGo** [comment]
解决了，被自带的webpack的postcss-loader配置覆盖了，重新用config-override重设下postcss-loader

**Comment by ChenHaoJie9527** [comment]
你好，我的项目中没有postcss-loader，使用这个插件px无法转化成vw的原因是什么嘞？
