### ISSUE TITLE
TypeError: postcss.atRule is not a constructor

### ISSUE THREAD

**Issue by huyanhai** [evrone/postcss-px-to-viewport#90]
"postcss": "^8.2.8",

**Comment by huyanhai** [comment]
"postcss-px-to-viewport": "^1.1.1",

**Comment by huyanhai** [comment]
"postcss": "^8.2.8","postcss-px-to-viewport": "^1.1.1", {landscape: true,}

**Comment by shuai4983958** [comment]
why?
